{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecoder.postgresqlName" . }}
  labels:
    {{- include "kubecoder.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  {{ .Values.postgresql.auth.usernameKey }}: {{ required "postgresql.auth.username is required" .Values.postgresql.auth.username | quote }}
  {{ .Values.postgresql.auth.passwordKey }}: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | quote }}
  {{ .Values.postgresql.auth.databaseKey }}: {{ required "postgresql.auth.database is required" .Values.postgresql.auth.database | quote }}
  {{ .Values.postgresql.auth.dsnKey }}: {{ include "kubecoder.databaseDSN" . | quote }}
{{- end }}
