<script setup lang="ts">
import { computed, onMounted, shallowRef, watch } from 'vue'
import { addSecretBinding, createSecret, deleteSecret, fetchAdminSecrets, fetchSecretTargets, removeSecretBinding, replaceSecret, type Secret, type SecretInput, type SecretOwner, type SecretScope, type SecretSortBy, type SecretStatusFilter, type SecretTarget, type SortOrder } from '../../api/secrets'
import { useAuth } from '../../composables/useAuth'
import { useNotifications } from '../../composables/useNotifications'
import { useRuntimeConfig } from '../../runtime/config'
import FilterCard from '../FilterCard.vue'
import SectionCard from '../SectionCard.vue'
import TablePaginationCard from '../TablePaginationCard.vue'
import SecretBindingsDialog from './SecretBindingsDialog.vue'
import SecretDeleteDialog from './SecretDeleteDialog.vue'
import SecretFormDialog from './SecretFormDialog.vue'
import SecretReplaceDialog from './SecretReplaceDialog.vue'
import SecretTable from './SecretTable.vue'

const props = defineProps<{ organizationId?: string; organizationSlug?: string }>()
const auth=useAuth();const config=useRuntimeConfig();const notifications=useNotifications()
const owner=computed<SecretOwner>(()=>({organizationID:props.organizationId,organizationSlug:props.organizationSlug}));const organizationMode=computed(()=>Boolean(props.organizationId||props.organizationSlug))
const items=shallowRef<Secret[]>([]);const targets=shallowRef<SecretTarget[]>([]);const total=shallowRef(0);const loading=shallowRef(false);const saving=shallowRef(false);const query=shallowRef('');const scope=shallowRef<'all'|SecretScope>('all');const status=shallowRef<'all'|Exclude<SecretStatusFilter,'NOT_EXPIRED'>>('all');const expired=shallowRef<'show'|'hide'>('hide');const page=shallowRef(1);const itemsPerPage=20
const sortBy=shallowRef<SecretSortBy>('variable_name');const sortOrder=shallowRef<SortOrder>('asc')
const createOpen=shallowRef(false);const replaceOpen=shallowRef(false);const bindingsOpen=shallowRef(false);const selected=shallowRef<Secret|null>(null);const deleteTarget=shallowRef<Secret|null>(null);const deleting=shallowRef(false);let revision=0
async function load(current=++revision){loading.value=true;try{const statusFilter:SecretStatusFilter|undefined=expired.value==='hide'?'NOT_EXPIRED':status.value==='all'?undefined:status.value;const result=await fetchAdminSecrets(config.apiBaseUrl,auth.accessToken.value,{query:query.value.trim(),scope:scope.value==='all'?undefined:scope.value,status:statusFilter,sort_by:sortBy.value,sort_order:sortOrder.value,limit:itemsPerPage,offset:(page.value-1)*itemsPerPage},owner.value);if(current!==revision)return;items.value=result.items??[];total.value=result.total}catch(error){if(current===revision)notifications.error('Secrets could not be loaded',error instanceof Error?error.message:undefined)}finally{if(current===revision)loading.value=false}}
function updateSort(nextSortBy:SecretSortBy,nextSortOrder:SortOrder){sortBy.value=nextSortBy;sortOrder.value=nextSortOrder;if(page.value!==1){page.value=1;return}void load()}
async function loadTargets(){try{targets.value=await fetchSecretTargets(config.apiBaseUrl,auth.accessToken.value,owner.value)}catch(error){notifications.error('Binding targets could not be loaded',error instanceof Error?error.message:undefined)}}
async function create(input:SecretInput){saving.value=true;try{await createSecret(config.apiBaseUrl,auth.accessToken.value,input,owner.value);createOpen.value=false;notifications.success('Secret created');await load()}catch(error){notifications.error('Secret could not be created',error instanceof Error?error.message:undefined)}finally{saving.value=false}}
function openReplace(secret:Secret){selected.value=secret;replaceOpen.value=true}function openBindings(secret:Secret){selected.value=secret;bindingsOpen.value=true}
async function replace(input:{value:string;expires_at:string|null}){if(!selected.value)return;saving.value=true;try{await replaceSecret(config.apiBaseUrl,auth.accessToken.value,selected.value.id,input,owner.value);replaceOpen.value=false;notifications.success('Secret value replaced');await load()}catch(error){notifications.error('Secret value could not be replaced',error instanceof Error?error.message:undefined)}finally{saving.value=false}}
async function addBinding(input:{target_type:'AGENT'|'REPOSITORY';target_id:string}){if(!selected.value)return;saving.value=true;try{await addSecretBinding(config.apiBaseUrl,auth.accessToken.value,selected.value.id,input,owner.value);await load();selected.value=items.value.find(item=>item.id===selected.value?.id)??null;notifications.success('Binding added')}catch(error){notifications.error('Binding could not be added',error instanceof Error?error.message:undefined)}finally{saving.value=false}}
async function removeBinding(bindingID:string){if(!selected.value)return;try{await removeSecretBinding(config.apiBaseUrl,auth.accessToken.value,selected.value.id,bindingID,owner.value);await load();selected.value=items.value.find(item=>item.id===selected.value?.id)??null;notifications.success('Binding removed')}catch(error){notifications.error('Binding could not be removed',error instanceof Error?error.message:undefined)}}
async function remove(){if(!deleteTarget.value)return;deleting.value=true;try{await deleteSecret(config.apiBaseUrl,auth.accessToken.value,deleteTarget.value.id,owner.value);deleteTarget.value=null;notifications.success('Secret deleted');if(items.value.length===1&&page.value>1)page.value-=1;else await load()}catch(error){notifications.error('Secret could not be deleted',error instanceof Error?error.message:undefined)}finally{deleting.value=false}}
function updateStatus(value:'all'|Exclude<SecretStatusFilter,'NOT_EXPIRED'>){status.value=value;if(value==='EXPIRED')expired.value='show'}
function updateExpired(value:'show'|'hide'){expired.value=value;if(value==='hide'&&status.value==='EXPIRED')status.value='all'}
watch([query,scope,status,expired],(_v,_o,onCleanup)=>{const current=++revision;if(page.value!==1){page.value=1;return}const timeout=window.setTimeout(()=>void load(current),300);onCleanup(()=>window.clearTimeout(timeout))});watch(page,()=>void load());watch([()=>props.organizationId,()=>props.organizationSlug],()=>{page.value=1;void Promise.all([load(),loadTargets()])});onMounted(()=>void Promise.all([load(),loadTargets()]))
</script>
<template><FilterCard title="Filters" subtitle="Search protected values"><v-text-field v-model="query" hide-details placeholder="Search secrets…" prepend-inner-icon="mdi-magnify" /><IconSelect v-if="organizationSlug" v-model="scope" hide-details :items="[{title:'All scopes',value:'all'},{title:'Platform',value:'PLATFORM'},{title:'Organization',value:'ORGANIZATION'}]" /><IconSelect :model-value="status" hide-details :items="[{title:'All statuses',value:'all'},{title:'Active',value:'ACTIVE'},{title:'Expiring soon',value:'EXPIRING_SOON'},{title:'Expired',value:'EXPIRED'}]" @update:model-value="updateStatus" /><IconSelect :model-value="expired" hide-details :items="[{title:'Hide expired',value:'hide'},{title:'Show expired',value:'show'}]" @update:model-value="updateExpired" /><v-spacer /><v-btn color="primary" variant="flat" prepend-icon="mdi-plus" @click="createOpen=true">Create secret</v-btn></FilterCard><SectionCard class="mt-4" :title="organizationMode ? 'Organization secrets' : 'Platform secrets'" :subtitle="`${total} protected values`"><SecretTable :items="items" :loading="loading" :sort-by="sortBy" :sort-order="sortOrder" :platform-readonly="Boolean(organizationSlug)" @sort="updateSort" @replace="openReplace" @bindings="openBindings" @delete="deleteTarget=$event" /></SectionCard><TablePaginationCard v-model="page" :total="total" :items-per-page="itemsPerPage" item-label="secrets" /><SecretFormDialog v-model="createOpen" :organization-mode="organizationMode" :saving="saving" @submit="create" /><SecretReplaceDialog v-model="replaceOpen" :secret="selected" :saving="saving" @submit="replace" /><SecretBindingsDialog v-model="bindingsOpen" :secret="selected" :targets="targets" :saving="saving" @add="addBinding" @remove="removeBinding" /><SecretDeleteDialog :secret="deleteTarget" :deleting="deleting" @close="deleteTarget=null" @confirm="remove" /></template>
