apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecoder-keycloak.fullname" . }}
  labels:
    {{- include "kubecoder-keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ required "keycloak.admin.username is required" .Values.keycloak.admin.username | quote }}
  admin-password: {{ required "keycloak.admin.password is required" .Values.keycloak.admin.password | quote }}
  demo-username: {{ required "realm.demoUser.username is required" .Values.realm.demoUser.username | quote }}
  demo-password: {{ required "realm.demoUser.password is required" .Values.realm.demoUser.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecoder-keycloak.postgresqlName" . }}
  labels:
    {{- include "kubecoder-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  username: {{ required "postgresql.username is required" .Values.postgresql.username | quote }}
  password: {{ required "postgresql.password is required" .Values.postgresql.password | quote }}
  database: {{ required "postgresql.database is required" .Values.postgresql.database | quote }}

